### ISSUE TITLE
Critical exception handling a packet

### ISSUE THREAD

**Issue by CurePindal** [clienthax/chococraft#15]
Found this in the log:

`````` Java
[19:11:26] [Server thread/ERROR]: There was a critical exception handling a packet on channel chococraft
java.lang.NullPointerException
    at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) ~[SimpleNetworkWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at chococraft.common.events.ChocoboPlayerTracker.sendLocalSetupUpdate(ChocoboPlayerTracker.java:91) ~[ChocoboPlayerTracker.class:?]
    at chococraft.common.events.ChocoboPlayerTracker.onPlayerLogout(ChocoboPlayerTracker.java:73) ~[ChocoboPlayerTracker.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_265_ChocoboPlayerTracker_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:575) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:433) ~[oi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:974) ~[nh.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:166) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]```

``````

**Comment by oaksvirals** [comment]
My players are having the same issue. They get disconnected from the server with a fatal error when this happens it seems.

**Comment by S0LiD-ST4T3** [comment]
found another post like this. nobody seems to care about this issue, and yet 5 years later this still happens. i'm starting to get really pissed off at clienthax for saying basically fuck all about this.
