### ISSUE TITLE
There was a critical exception handling a packet on channel chococraft

### ISSUE THREAD

**Issue by oaksvirals** [clienthax/chococraft#17]
Players on my server keep geeting A Fatal error and are disconnected from the server.

`[Server thread/ERROR]: There was a critical exception handling a packet on channel chococraft
java.lang.NullPointerException
    at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) ~[SimpleNetworkWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at chococraft.common.events.ChocoboPlayerTracker.sendLocalSetupUpdate(ChocoboPlayerTracker.java:91) ~[ChocoboPlayerTracker.class:?]
    at chococraft.common.events.ChocoboPlayerTracker.onPlayerLogout(ChocoboPlayerTracker.java:73) ~[ChocoboPlayerTracker.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_93_ChocoboPlayerTracker_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:575) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:433) ~[oi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:974) ~[nh.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]`

**Comment by ajthemacboy** [comment]
I used to get this too, but now I think it was because of another mod conflicting. I may have changed some ID in config to fix it, not sure.

**Comment by S0LiD-ST4T3** [comment]
5 years later, still happens. ffs. looks like nobody gives a grand shit
